# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
reports:
  exclude_contracts:
    - SafeMath

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.2
compiler:
  evm_version: istanbul
  solc:
    version: 0.8.4
    optimizer:
      enabled: true
      runs: 1
    remappings:
      - '@openzeppelin=/home/oem/.brownie/packages/OpenZeppelin/openzeppelin-contracts@4.3.2'

network:
  default: development # the default network that brownie connects to
  settings:
    gas_limit: 'auto'
    gas_price: 'auto'
    persist: true
    reverting_tx_gas_limit: false # if false, reverting tx's will raise without broadcasting
  networks:
    # any settings given here will replace the defaults
    development:
      host: http://127.0.0.1
      gas_price: 0
      persist: false
      reverting_tx_gas_limit: 12000000000000
      test_rpc:
        cmd: ganache-cli
        port: 8545
        gas_limit: 12000000000000
        accounts: 10
        evm_version: istanbul
        mnemonic: brownie

dotenv: .env
